### ISSUE TITLE
Splunk Cloud support

### ISSUE THREAD

**Issue by ericzinnikas** [1Password/events-api-splunk#12]
I'm sure there are many folks using Splunk Cloud and I would be interested to know if getting Cloud support for this add-on is on your roadmap? I see the readme mentions this already "meets Splunk's AppInspect requirements" -- https://dev.splunk.com/enterprise/docs/releaseapps/cloudvetting/

I ran appinspect manually, and it seems to mainly be warning about a missing `version="1.1"` attribute from the "form" and "dashboard" root elements in your 3 XML views.

Thanks!

**Comment by meek** [comment]
Thanks Eric! Yes, Splunk Cloud support is definitely on our roadmap, and we're working through a few additional requirements there. Can't make any promises on exactly when it will be available, but watch this space!

**Comment by meek** [comment]
Hey @ericzinnikas, thanks again for bringing this up - I'm happy to say that 1Password Events Reporting for Splunk version 1.5.3 is now approved for Splunk Cloud! https://splunkbase.splunk.com/app/5632/

**Comment by ericzinnikas** [comment]
Hey @meek I'm wondering if you were able to deploy/test this in a cloud environment? We're having some trouble enabling the scripted inputs, they don't seem visible in the cloud UI on the "Data inputs" page (I'm speaking w/Splunk support about this as well, but they suggested we check with you first).

**Comment by mrtc0** [comment]
Hi, @meek I'm currently using Splunk Cloud "Classic". 

After installing on IDM, I asked support if I could enable the signin_attempts and item_usages scripts, but it wasn't to be possible...

Either the script must be enabled by default with an Add-On, or the user must create a Private App and re-upload it to Splunk with a request for review.

It would be helpful if you could change it to be enabled for scripts by default.

**Comment by meek** [comment]
Hey @mrtc0, I'm so sorry for the delayed response here - I had somehow missed your comment. We ran into a few stumbling blocks with the "Classic" stack on Splunk Cloud, and we now have detailed docs on how to use our add-on in that stack. Take a look here:

https://support.1password.com/events-reporting-splunk-classic/

Additionally, ensure you're on the latest version of the 1Password Events Reporting for Splunk app: https://splunkbase.splunk.com/app/5632/#/overview

**Comment by ericzinnikas** [comment]
Thanks @meek -- do you know when `1.7.3` will be available for Splunk Cloud?
```
COMPATIBILITY
This version of the app (1.7.3) is not available for Splunk Cloud. However, version 1.7.2 of this app is available for Splunk Cloud.
```

**Comment by mrtc0** [comment]
@meek Thank you for your reply. 

We've been able to successfully collect events since version 1.7.0 of 1Password Events Reporting for Splunk!
Thank you for your support.

**Comment by meek** [comment]
> Thanks @meek -- do you know when `1.7.3` will be available for Splunk Cloud?
> 
> ```
> COMPATIBILITY
> This version of the app (1.7.3) is not available for Splunk Cloud. However, version 1.7.2 of this app is available for Splunk Cloud.
> ```

@ericzinnikas 1.7.3 should hopefully be approved for Splunk Cloud soon! The only difference there is using separate index macros for the two data types in case you put them on separate indexes. 1.7.2. should work great for ingesting the data in the meantime.

**Comment by meek** [comment]
> @meek Thank you for your reply.
> 
> We've been able to successfully collect events since version 1.7.0 of 1Password Events Reporting for Splunk app! Thank you for your support.

@mrtc0 fantastic! Thanks for letting us know that you've got it up and running! 🎉

**Comment by ericzinnikas** [comment]
Hey @meek finally getting back to look at this -- I just installed `1.8.0` and went through the setup flow. After it finishes ("Events API Reporting for Splunk has been successfully setup"), when viewing the 1password app, the "Configuration" tab just takes me back to the initial setup flow, which indicates to me something isn't being finalized in the setup process (I don't see any network/JS errors).

Additionally, I am on the Victoria experience but my Data inputs screen has no "scripted inputs" section. I will be following up with Splunk support on this, but figured I'd ask here in case you've seen this issue too.
